# Generated by Django 6.1.1 on 2026-09-07 18:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.CharField(max_length=64)),
                ('action', models.CharField(max_length=64)),
                ('target', models.CharField(max_length=255)),
                ('before', models.JSONField(blank=True, null=True)),
                ('after', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'audit',
            },
        ),
        migrations.CreateModel(
            name='Crawl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(db_index=True, max_length=48)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='running', max_length=12)),
                ('pages_total', models.IntegerField(default=0)),
                ('sitemap_url', models.CharField(blank=True, default='', max_length=500)),
                ('sitemap_urls', models.JSONField(default=list)),
                ('robots_txt', models.TextField(blank=True, default='')),
                ('external_checks', models.JSONField(default=dict)),
                ('note', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(max_length=16)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('exit_code', models.IntegerField(blank=True, null=True)),
                ('dry_run', models.IntegerField(default=0)),
                ('trigger', models.CharField(default='manual', max_length=64)),
                ('site', models.CharField(blank=True, default='', max_length=48)),
                ('error', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'runs',
            },
        ),
        migrations.CreateModel(
            name='SeoAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=48, unique=True)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('data', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('source', models.CharField(default='manual', max_length=16)),
                ('category', models.CharField(blank=True, default='', max_length=60)),
                ('relevance', models.IntegerField(default=50)),
                ('why', models.CharField(blank=True, default='', max_length=300)),
                ('site', models.CharField(blank=True, default='', max_length=48)),
                ('status', models.CharField(default='suggested', max_length=12)),
                ('position', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('post_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'topics',
            },
        ),
        migrations.CreateModel(
            name='ApiToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LogLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(default=django.utils.timezone.now)),
                ('stream', models.CharField(default='stdout', max_length=8)),
                ('line', models.TextField()),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.run')),
            ],
            options={
                'db_table': 'logs',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1000)),
                ('final_url', models.CharField(blank=True, default='', max_length=1000)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('redirect_chain', models.JSONField(default=list)),
                ('content_type', models.CharField(blank=True, default='', max_length=100)),
                ('response_ms', models.IntegerField(blank=True, null=True)),
                ('bytes', models.IntegerField(default=0)),
                ('depth', models.IntegerField(default=0)),
                ('in_sitemap', models.BooleanField(default=False)),
                ('robots_blocked', models.BooleanField(default=False)),
                ('fetch_error', models.CharField(blank=True, default='', max_length=300)),
                ('title', models.CharField(blank=True, default='', max_length=500)),
                ('meta_description', models.CharField(blank=True, default='', max_length=1000)),
                ('meta_robots', models.CharField(blank=True, default='', max_length=100)),
                ('canonical', models.CharField(blank=True, default='', max_length=1000)),
                ('lang', models.CharField(blank=True, default='', max_length=16)),
                ('h1', models.JSONField(default=list)),
                ('h2_count', models.IntegerField(default=0)),
                ('word_count', models.IntegerField(default=0)),
                ('text_hash', models.CharField(blank=True, default='', max_length=32)),
                ('text_sample', models.TextField(blank=True, default='')),
                ('internal_links', models.JSONField(default=list)),
                ('external_links', models.JSONField(default=list)),
                ('images_total', models.IntegerField(default=0)),
                ('images_missing_alt', models.IntegerField(default=0)),
                ('jsonld_types', models.JSONField(default=list)),
                ('jsonld_error', models.CharField(blank=True, default='', max_length=200)),
                ('mixed_content', models.IntegerField(default=0)),
                ('security_headers', models.JSONField(default=dict)),
                ('wp_base', models.CharField(blank=True, default='', max_length=32)),
                ('wp_id', models.IntegerField(blank=True, null=True)),
                ('crawl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='core.crawl')),
            ],
            options={
                'indexes': [models.Index(fields=['crawl', 'url'], name='core_page_crawl_i_7fa67f_idx')],
            },
        ),
    ]
