# Generated by Django 6.1.1 on 2026-09-07 19:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=48, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('products', models.JSONField(default=list)),
                ('services', models.JSONField(default=list)),
                ('industries', models.JSONField(default=list)),
                ('audience', models.TextField(blank=True, default='')),
                ('locations', models.JSONField(default=list)),
                ('markets', models.JSONField(default=list)),
                ('priorities', models.JSONField(default=list)),
                ('brand_voice', models.TextField(blank=True, default='')),
                ('facts', models.JSONField(default=list)),
                ('competitors', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Change',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(db_index=True, max_length=48)),
                ('kind', models.CharField(max_length=32)),
                ('wp_base', models.CharField(blank=True, default='', max_length=32)),
                ('wp_id', models.IntegerField(blank=True, null=True)),
                ('field', models.CharField(blank=True, default='', max_length=32)),
                ('before', models.JSONField(blank=True, null=True)),
                ('after', models.JSONField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, default='')),
                ('source', models.CharField(default='ai', max_length=32)),
                ('status', models.CharField(db_index=True, default='proposed', max_length=12)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decided_by', models.CharField(blank=True, default='', max_length=64)),
                ('error', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Brief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(db_index=True, max_length=48)),
                ('title', models.CharField(max_length=200)),
                ('primary_keyword', models.CharField(blank=True, default='', max_length=120)),
                ('secondary_keywords', models.JSONField(default=list)),
                ('intent', models.CharField(default='informational', max_length=24)),
                ('content_type', models.CharField(default='blog', max_length=24)),
                ('audience', models.TextField(blank=True, default='')),
                ('outline', models.JSONField(default=list)),
                ('entities', models.JSONField(default=list)),
                ('faqs', models.JSONField(default=list)),
                ('internal_links', models.JSONField(default=list)),
                ('cta', models.TextField(blank=True, default='')),
                ('word_target', models.IntegerField(default=900)),
                ('custom_instructions', models.TextField(blank=True, default='')),
                ('prompt_version', models.CharField(blank=True, default='', max_length=16)),
                ('draft_title', models.CharField(blank=True, default='', max_length=200)),
                ('draft_meta', models.CharField(blank=True, default='', max_length=300)),
                ('draft_html', models.TextField(blank=True, default='')),
                ('qa', models.JSONField(default=dict)),
                ('status', models.CharField(db_index=True, default='brief', max_length=12)),
                ('post_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.topic')),
            ],
        ),
    ]
