# Generated by Django 6.1.1 on 2026-09-07 19:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_businessprofile_change_brief'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(db_index=True, max_length=48)),
                ('name', models.CharField(max_length=160)),
                ('parent_topic', models.CharField(blank=True, default='', max_length=160)),
                ('intent', models.CharField(default='informational', max_length=24)),
                ('role', models.CharField(default='cluster', max_length=12)),
                ('action', models.CharField(default='', max_length=12)),
                ('target_url', models.CharField(blank=True, default='', max_length=1000)),
                ('target_wp_base', models.CharField(blank=True, default='', max_length=32)),
                ('target_wp_id', models.IntegerField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, default='')),
                ('priority', models.IntegerField(default=50)),
                ('approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(db_index=True, max_length=48)),
                ('text', models.CharField(max_length=160)),
                ('source', models.CharField(default='manual', max_length=12)),
                ('intent', models.CharField(blank=True, default='', max_length=24)),
                ('relevance', models.IntegerField(default=50)),
                ('commercial', models.IntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('found_on', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('cluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='keywords', to='core.cluster')),
            ],
            options={
                'unique_together': {('site', 'text')},
            },
        ),
    ]
