# Generated by Django 6.1.1 on 2026-09-07 20:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cluster_keyword'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(db_index=True, max_length=48)),
                ('source', models.CharField(max_length=16)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('rows', models.IntegerField(default=0)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Ga4Row',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(db_index=True, max_length=48)),
                ('date', models.DateField()),
                ('landing_page', models.CharField(max_length=1000)),
                ('channel', models.CharField(default='', max_length=64)),
                ('sessions', models.IntegerField(default=0)),
                ('users', models.IntegerField(default=0)),
                ('conversions', models.FloatField(default=0)),
            ],
            options={
                'indexes': [models.Index(fields=['site', 'date'], name='core_ga4row_site_85c7cd_idx'), models.Index(fields=['site', 'landing_page'], name='core_ga4row_site_7653d0_idx')],
            },
        ),
        migrations.CreateModel(
            name='GscRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(db_index=True, max_length=48)),
                ('date', models.DateField()),
                ('query', models.CharField(max_length=300)),
                ('page', models.CharField(max_length=1000)),
                ('clicks', models.IntegerField(default=0)),
                ('impressions', models.IntegerField(default=0)),
                ('ctr', models.FloatField(default=0)),
                ('position', models.FloatField(default=0)),
            ],
            options={
                'indexes': [models.Index(fields=['site', 'date'], name='core_gscrow_site_1a093d_idx'), models.Index(fields=['site', 'query'], name='core_gscrow_site_1849e7_idx'), models.Index(fields=['site', 'page'], name='core_gscrow_site_63b1dc_idx')],
            },
        ),
    ]
