# Generated by Django 6.1.1 on 2026-09-07 21:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sync_ga4row_gscrow'),
    ]

    operations = [
        migrations.CreateModel(
            name='LlmCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('model', models.CharField(max_length=64)),
                ('purpose', models.CharField(blank=True, default='', max_length=32)),
                ('prompt_tokens', models.IntegerField(default=0)),
                ('completion_tokens', models.IntegerField(default=0)),
                ('cost_usd', models.FloatField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='brief',
            name='link_plan',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='brief',
            name='schema_jsonld',
            field=models.JSONField(default=dict),
        ),
    ]
