# Generated by Django 6.1.1 on 2026-09-07 21:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_llmcall_brief_link_plan_brief_schema_jsonld'),
    ]

    operations = [
        migrations.CreateModel(
            name='SerpResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(db_index=True, max_length=200)),
                ('country', models.CharField(blank=True, default='', max_length=4)),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('results', models.JSONField(default=list)),
            ],
        ),
        migrations.AddField(
            model_name='cluster',
            name='serp',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='page',
            name='cls',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='inp_ms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='lcp_ms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='psi_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='psi_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='tbt_ms',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
